// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AudioUnlock","status":true,"description":"✅ 強制解鎖 Edge / Safari / iOS 上的音訊播放，解決 BGM、SE 無聲問題（包含 iOS 特化修正）v3","parameters":{}},
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1280","screenHeight":"720","changeWindowWidthTo":"1920","changeWindowHeightTo":"1080","renderingMode":"auto","alwaysDash":"off"}},
{"name":"GoogleSheetLogger","status":true,"description":"Integrates Google Sheet Logging for RPG Maker MV.\r\nLogs player actions, results, and execution times automatically.","parameters":{}},
{"name":"BattleSkillWindow","status":true,"description":"戰鬥中技能視窗改為單欄、直向清單，並移至左側 (示範版)","parameters":{}},
{"name":"show enemy","status":true,"description":"顯示敵人資訊插件 - 顯示敵人的詳細數值如HP、攻擊力、防禦力等，支持多個敵人顯示。","parameters":{"BarWidth":"120","ShowCriticalInfoSwitch":"5"}},
{"name":"CustomBattlePlugin","status":true,"description":"Modify Battle Mode to Handle Negative HP with Recovery","parameters":{}},
{"name":"PlayerDataFix","status":true,"description":"顯示玩家資訊插件 - 顯示玩家的詳細數值如HP、MP、攻擊力、防禦力等，支持開關控制暴擊資訊。","parameters":{"ShowCriticalInfoSwitch":"5"}},
{"name":"YEP_EventMiniLabel","status":true,"description":"v1.12 Creates miniature-sized labels over events to allow\nyou to insert whatever text you'd like in them.","parameters":{"Default Show":"false","Minimum Width":"136","Font Size":"30","X Buffer":"0","Y Buffer":"36","Battle Transition":"false"}},
{"name":"YEP_EventMiniLabel_fixed","status":true,"description":"顯示玩家頭上可動態更新的標籤，並可透過 Show/HideMiniLabel 同步隱藏 (最終整合)","parameters":{}},
{"name":"DynamicVideoPlayer","status":true,"description":"在地圖上播放影片，不影響 UI 和對話框，並確保無縫循環","parameters":{}},
{"name":"MULI_WindowTextField","status":true,"description":"仿原生文字框輸入，運用透明<input>","parameters":{"window":"","defaultWidth":"480","minWidth":"240","maxWidth":"0","windowHeight":"0","textField":"","textFieldY":"0","textFieldAlign":"center","button":"","buttonImage":"TextFieldButton","buttonHeight":"48","buttonAlign":"center","buttonCancel":"","buttonCancelX":"0","buttonCancelWidth":"96","buttonOk":"","buttonOkX":"96","buttonOkWidth":"96","text":"","selectionColor":"","textAlign":"left","nameEdit":"","hideTable":"false"}},
{"name":"For IOS keybord","status":true,"description":"[iOS] 修正Safari/Chrome鍵盤 + 全螢幕 + 音訊解鎖","parameters":{}},
{"name":"CustomTimer","status":true,"description":"計時器插件：可自由開始/停止，結果存入指定變數","parameters":{}}
];
